[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "v4-hooks-public/=lib/v4-hooks-public/src/",
    "reactive-lib/=lib/reactive-lib/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/"
]
